# Generated by Django 5.2.2 on 2025-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('admin', 'Admin'), ('hr', 'HR'), ('carer', 'Carer'), ('client', 'Client'), ('family', 'Family'), ('auditor', 'Auditor'), ('tutor', 'Tutor'), ('assessor', 'Assessor'), ('iqa', 'IQA'), ('eqa', 'EQA')], default='carer', max_length=20),
        ),
    ]
