# Generated by Django 5.2 on 2025-04-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('account_suspended', 'Account Suspended'), ('account_activated', 'Account Activated'), ('course_access', 'Course Access'), ('assignment_submission', 'Assignment Submission'), ('system', 'System Event'), ('user_management', 'User Management'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('group_member_added', 'Group Member Added'), ('group_member_removed', 'Group Member Removed'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted')], max_length=50),
        ),
    ]
