# Generated by Django 5.2.2 on 2025-07-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_rolepermission_role'),
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_locked'], name='users_custo_is_lock_0448a0_idx'),
        ),
    ]
