# Generated by Django 5.2.2 on 2025-08-02 00:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_bio_customuser_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.profile_picture_upload_path),
        ),
    ]
