# Generated by Django 5.2.2 on 2025-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('text', 'Text'), ('file', 'File'), ('link', 'Link')], default='video', max_length=20),
        ),
    ]
