# Generated by Django 5.2.2 on 2025-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_end_date_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
