# Generated by Django 5.2.2 on 2025-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_assignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_text',
            field=models.TextField(blank=True),
        ),
    ]
